# Generated by Django 3.2.7 on 2021-10-10 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Producto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.CharField(max_length=50, verbose_name='Nombre proveedor')),
                ('telefono', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedors',
            },
        ),
        migrations.CreateModel(
            name='AsignacionProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Producto.productoservicio')),
                ('id_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Proveedor.proveedor')),
            ],
            options={
                'verbose_name': 'AsignacionProveedor',
                'verbose_name_plural': 'AsignacionProveedors',
                'unique_together': {('id_proveedor', 'id_producto')},
            },
        ),
    ]
