# Generated by Django 3.2.7 on 2021-10-18 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proveedor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='direccion',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
