# Generated by Django 3.2.7 on 2021-10-18 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proveedor', '0002_proveedor_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='direccion',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
