# Generated by Django 3.2.7 on 2021-10-20 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0002_auto_20211017_2125'),
        ('Proveedor', '0003_alter_proveedor_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacionproveedor',
            name='id_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Product_Supplier', to='Producto.productoservicio'),
        ),
        migrations.AlterField(
            model_name='asignacionproveedor',
            name='id_proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Supplier_Product', to='Proveedor.proveedor'),
        ),
    ]
