# Generated by Django 3.2.7 on 2021-10-24 02:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0008_alter_productoservicio_cantidad'),
        ('Proveedor', '0004_auto_20211020_2107'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoteProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingeso', models.DateTimeField(default=django.utils.timezone.now)),
                ('cantidad', models.IntegerField()),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Producto_Lote', to='Producto.productoservicio')),
                ('proveedr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Proveedor_Lote', to='Proveedor.proveedor')),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
            },
        ),
    ]
