# Generated by Django 3.2.7 on 2021-10-24 03:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Proveedor', '0005_loteproducto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loteproducto',
            name='fecha_ingeso',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
