# Generated by Django 3.2.7 on 2021-10-24 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Proveedor', '0006_alter_loteproducto_fecha_ingeso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loteproducto',
            old_name='proveedr',
            new_name='proveedor',
        ),
    ]
