# Generated by Django 3.2.7 on 2021-10-25 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Proveedor', '0007_rename_proveedr_loteproducto_proveedor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loteproducto',
            old_name='fecha_ingeso',
            new_name='fecha_ingreso',
        ),
    ]
