# Generated by Django 3.2.7 on 2021-10-10 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Compra', '0001_initial'),
        ('PaginaVenta', '0001_initial'),
        ('Producto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle',
            name='id_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Producto.productoservicio'),
        ),
        migrations.AddField(
            model_name='compra',
            name='id_sitio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PaginaVenta.paginaventas'),
        ),
    ]
