# Generated by Django 3.2.8 on 2021-10-24 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compra', '0004_auto_20211021_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='estado',
            field=models.CharField(choices=[('0', 'Compra realizado'), ('1', 'Error de compra'), ('2', 'Compra cancelada'), ('3', 'En proceso')], default='3', max_length=1, verbose_name='Estado'),
        ),
    ]
