# Generated by Django 3.2.7 on 2021-10-10 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaginaVentas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sitio', models.CharField(max_length=50, verbose_name='Sitio')),
                ('descripcion', models.CharField(max_length=50, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'PaginaVentas',
                'verbose_name_plural': 'PaginaVentass',
            },
        ),
        migrations.CreateModel(
            name='Suscripciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pagina_ventas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PaginaVenta.paginaventas')),
            ],
            options={
                'verbose_name': 'Suscripciones',
                'verbose_name_plural': 'Suscripcioness',
            },
        ),
    ]
