# Generated by Django 3.2.7 on 2021-10-16 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaginaVenta', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paginaventas',
            name='no_cuenta',
            field=models.IntegerField(default=0, unique=True, verbose_name='Numero de cuenta'),
        ),
    ]
