# Generated by Django 3.2.7 on 2021-10-16 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaginaVenta', '0003_paginaventas_no_cuenta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paginaventas',
            name='nombre_sitio',
            field=models.CharField(max_length=50, unique=True, verbose_name='Sitio'),
        ),
    ]
