# Generated by Django 3.2.7 on 2021-10-16 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaginaVenta', '0004_alter_paginaventas_nombre_sitio'),
    ]

    operations = [
        migrations.AddField(
            model_name='paginaventas',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
