# Generated by Django 3.2.7 on 2021-10-18 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PaginaVenta', '0005_paginaventas_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscripciones',
            name='id_pagina_ventas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suscripciones_pagina_venta', to='PaginaVenta.paginaventas'),
        ),
        migrations.AlterField(
            model_name='suscripciones',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_pagina_venta', to=settings.AUTH_USER_MODEL),
        ),
    ]
