# Generated by Django 3.2.7 on 2021-10-10 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('0', 'Administrador'), ('1', 'Usuario')], default='0', max_length=1, verbose_name='Rol'),
        ),
    ]
