# Generated by Django 3.2.7 on 2021-10-14 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_alter_usuario_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='about_me',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Sobre mi'),
        ),
    ]
