# Generated by Django 3.2.7 on 2021-10-14 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_usuario_about_me'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='about_me',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
