# Generated by Django 3.2.7 on 2021-10-21 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_alter_usuario_about_me'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='no_cuenta',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
