# Generated by Django 3.2.8 on 2021-10-29 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_usuario_no_cuenta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='no_cuenta',
        ),
    ]
