# Generated by Django 3.2.7 on 2021-10-10 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PaginaVenta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='ProductoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('cantidad', models.IntegerField()),
                ('precio', models.FloatField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='Portada')),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto_categoria', to='Producto.categoria')),
                ('id_pagina_ventas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PaginaVenta.paginaventas')),
            ],
            options={
                'verbose_name': 'ProductoServicio',
                'verbose_name_plural': 'ProductoServicios',
            },
        ),
    ]
