# Generated by Django 3.2.7 on 2021-10-17 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PaginaVenta', '0005_paginaventas_status'),
        ('Producto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoservicio',
            name='id_categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='producto_categoria', to='Producto.categoria'),
        ),
        migrations.AlterField(
            model_name='productoservicio',
            name='id_pagina_ventas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PaginaVenta.paginaventas'),
        ),
    ]
