# Generated by Django 3.2.7 on 2021-10-18 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PaginaVenta', '0005_paginaventas_status'),
        ('Producto', '0002_auto_20211018_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoservicio',
            name='id_pagina_ventas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_pagina_ventas', to='PaginaVenta.paginaventas'),
        ),
    ]
