# Generated by Django 3.2.7 on 2021-10-18 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0003_alter_productoservicio_id_pagina_ventas'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoservicio',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
