# Generated by Django 3.2.7 on 2021-10-20 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0002_auto_20211017_2125'),
        ('Producto', '0004_productoservicio_descripcion'),
    ]

    operations = [
    ]
