# Generated by Django 3.2.7 on 2021-10-21 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PaginaVenta', '0006_auto_20211018_1650'),
        ('Producto', '0005_merge_20211020_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoservicio',
            name='id_pagina_ventas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_pagina_ventas', to='PaginaVenta.paginaventas'),
        ),
    ]
