# Generated by Django 3.2.7 on 2021-10-24 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0005_merge_20211020_2324'),
        ('Producto', '0006_alter_productoservicio_id_pagina_ventas'),
    ]

    operations = [
    ]
